- project:
    templates:
      - check-requirements
      - openstack-python3-zed-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - sushy-tools-tempest-bios-redfish-pxe
        - sushy-tools-tempest-uefi-redfish-vmedia
    gate:
      jobs:
        - sushy-tools-tempest-bios-redfish-pxe
        - sushy-tools-tempest-uefi-redfish-vmedia
